const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=()=>`${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`,KEY='igoogle-revival-v2';
const themes=[['bus','Bus Stop'],['classic','Classic'],['beach','Beach'],['city','City Scape'],['dreams','Sweet Dreams'],['tea','Tea House'],['seasonal','Seasonal Scape'],['sunrise','Sunrise'],['night','Night Sky']];
const catalog=[
 ['weather','Weather','☔','News','Live conditions and a four-day forecast.'],['news','Top Stories','📰','News','Live headlines and topic search.'],['rss','Custom RSS Feed','◉','News','Read any public RSS or Atom feed.'],
 ['gmail','Gmail','✉','Google','Inbox shortcuts and compose actions.'],['calendar','Google Calendar','▣','Google','Month view with personal local events.'],['translate','Google Translate','文','Google','Send text directly to Google Translate.'],['maps','Google Maps','⌖','Google','Search places and get directions.'],['links','Google Services','G','Google','Fast links to classic Google products.'],
 ['bookmarks','Bookmarks','★','Tools','Save and organize favorite links.'],['todo','To-do List','✓','Tools','A persistent personal task list.'],['notes','Sticky Notes','▤','Tools','A notepad that saves as you type.'],['clock','World Clock','◷','Tools','Local time and configurable time zone.'],['calculator','Calculator','＋','Tools','A fully working pocket calculator.'],['converter','Unit Converter','↔','Tools','Convert common lengths and weights.'],
 ['wikipedia','Wikipedia','W','Reference','Search Wikipedia from your homepage.'],['dictionary','Dictionary','Aa','Reference','Look up definitions and pronunciations.'],
 ['youtube','YouTube','▶','Entertainment','Search and launch YouTube videos.'],['photos','Photo Frame','▧','Entertainment','Display an image from the web.'],['quote','Quote of the Day','❝','Lifestyle','A rotating collection of memorable quotes.'],['countdown','Countdown','⌛','Lifestyle','Count down to an important date.'],
 ['stocks','Google Finance','↗','Finance','Track a personal stock watchlist.'],['tictactoe','Tic-Tac-Toe','○','Games','The classic two-player game.'],['sudoku','Mini Sudoku','▦','Games','A compact number puzzle.']
].map(([id,name,icon,category,desc])=>({id,name,icon,category,desc}));
const makeWidgets=items=>items.map(([type,column])=>({instance:uid(),type,column,config:{},minimized:false}));
const defaults={version:2,theme:'bus',activeTab:'home',tabs:[{id:'home',name:'Home',layout:3,widgets:makeWidgets([['weather',0],['gmail',0],['bookmarks',0],['news',1],['calendar',1],['clock',1],['todo',2],['notes',2],['stocks',2]])},{id:'news-tab',name:'News',layout:3,widgets:makeWidgets([['news',0],['rss',1],['weather',2]])}]};
let state=load(),dragged=null,category='Featured',toastTimer;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.version===2&&Array.isArray(x.tabs))return x}catch{}return structuredClone(defaults)}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function tab(){return state.tabs.find(x=>x.id===state.activeTab)||state.tabs[0]}function widget(id){return tab().widgets.find(x=>x.instance===id)}function info(type){return catalog.find(x=>x.id===type)}
function toast(message){const x=$('#toast');x.textContent=message;x.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove('show'),2200)}
function render(){renderTheme();renderTabs();renderDashboard();save()}function renderTheme(){$('#masthead').className=`masthead theme-${tab().theme||state.theme}`}
function renderTabs(){$('#tabs').innerHTML=state.tabs.map(x=>`<button class="tab ${x.id===state.activeTab?'active':''}" data-tab="${x.id}">${esc(x.name)} <span class="tab-menu">▾</span></button>`).join('')}
function renderDashboard(){const t=tab(),dash=$('#dashboard');dash.style.setProperty('--columns',t.layout);dash.innerHTML='';$('#empty-dashboard').hidden=!!t.widgets.length;dash.hidden=!t.widgets.length;for(let col=0;col<t.layout;col++){const c=document.createElement('section');c.className='dashboard-column';c.dataset.column=col;t.widgets.filter(w=>Math.min(w.column,t.layout-1)===col).forEach(w=>c.append(renderWidget(w)));dash.append(c)}dropZones()}
function renderWidget(w){const d=info(w.type),node=$('#gadget-template').content.firstElementChild.cloneNode(true);node.dataset.instance=w.instance;node.classList.toggle('minimized',w.minimized);$('.gadget-icon',node).textContent=d?.icon||'□';$('.gadget-header h2',node).textContent=w.config.title||d?.name||w.type;const content=$('.gadget-content',node);try{content.innerHTML=contentFor(w)}catch(e){content.innerHTML=`<p class="error">This gadget could not load: ${esc(e.message)}</p>`}queueMicrotask(()=>activate(w,node));return node}
function form(type,placeholder,value,button='Search'){return`<form class="widget-form" data-form="${type}"><input name="query" value="${esc(value||'')}" placeholder="${placeholder}"><button>${button}</button></form><div class="search-output muted">Enter a search above.</div>`}
function contentFor(w){const c=w.config;switch(w.type){
 case'weather':return`<form class="widget-form" data-form="weather"><input name="city" value="${esc(c.city||'New York')}" aria-label="City"><button>Go</button></form><div class="weather-output loading">Loading weather…</div>`;
 case'news':return`<form class="widget-form" data-form="news"><input name="query" value="${esc(c.query||'technology')}" aria-label="News topic"><button>Go</button></form><ul class="list news-list"><li class="loading">Loading headlines…</li></ul>`;
 case'rss':return`<form class="widget-form" data-form="rss"><input name="url" value="${esc(c.url||'https://feeds.bbci.co.uk/news/rss.xml')}" aria-label="Feed URL"><button>Load</button></form><ul class="list rss-list"><li class="muted">Enter a public RSS or Atom URL.</li></ul>`;
 case'gmail':return`<div class="widget-form"><a class="small-button" target="_blank" rel="noopener" href="https://mail.google.com/mail/u/0/#inbox">Open inbox</a><a class="small-button" target="_blank" rel="noopener" href="https://mail.google.com/mail/u/0/#compose">Compose</a></div><ul class="list"><li class="mail-item"><span>✉</span><a target="_blank" rel="noopener" href="https://mail.google.com/">Sign in to view your Gmail inbox</a><small>Google</small></li><li class="muted">For your privacy, this revival never reads account data.</li></ul>`;
 case'calendar':return calendar(c.monthOffset||0,c.events||[]);
 case'bookmarks':return`<form class="widget-form" data-form="bookmark"><input name="label" placeholder="Name" required><input name="url" placeholder="https://" required><button>Add</button></form><ul class="list bookmarks-list">${(c.items||[{label:'Google',url:'https://google.com'},{label:'Wikipedia',url:'https://wikipedia.org'}]).map((x,i)=>`<li><a href="${esc(url(x.url))}" target="_blank" rel="noopener">${esc(x.label)}</a><button data-bookmark-remove="${i}">×</button></li>`).join('')}</ul>`;
 case'todo':return`<form class="todo-add widget-form" data-form="todo"><input name="task" placeholder="New task" required><button>Add</button></form><ul class="list">${(c.items||[]).map((x,i)=>`<li class="todo-item ${x.done?'done':''}"><input type="checkbox" data-todo-check="${i}" ${x.done?'checked':''}><span>${esc(x.text)}</span><button data-todo-remove="${i}">×</button></li>`).join('')||'<li class="muted">Nothing to do. Enjoy the day.</li>'}</ul>`;
 case'notes':return`<textarea class="note-area" data-note placeholder="Write a note…">${esc(c.text||'')}</textarea>`;
 case'clock':return`<div class="clock-face" data-clock>--:--:--</div><div class="clock-date" data-clock-date></div><select class="widget-input" data-timezone><option value="local">Local time</option>${['America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Europe/London','Europe/Paris','Asia/Tokyo','Australia/Sydney'].map(z=>`<option ${c.zone===z?'selected':''}>${z}</option>`).join('')}</select>`;
 case'calculator':return`<input class="calc-display" value="${esc(c.display||'0')}" readonly><div class="calc-grid">${['C','(',')','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','⌫','='].map(k=>`<button data-calc="${k}">${k}</button>`).join('')}</div>`;
 case'converter':return converter(c);case'wikipedia':return form('wikipedia','Search Wikipedia',c.query);case'dictionary':return form('dictionary','Look up a word',c.query);
 case'translate':return`<form data-form="translate"><textarea class="note-area" name="text" placeholder="Enter text">${esc(c.text||'')}</textarea><div class="widget-form"><select name="lang"><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option><option value="ja">Japanese</option></select><button>Translate</button></div></form>`;
 case'youtube':return form('youtube','Search YouTube',c.query);case'maps':return`<form class="widget-form" data-form="maps"><input name="query" value="${esc(c.query||'')}" placeholder="Search a place"><button>Map</button></form><div class="quick-links"><a target="_blank" rel="noopener" href="https://maps.google.com/">Explore Maps</a><a target="_blank" rel="noopener" href="https://maps.google.com/maps?dirflg=d">Get directions</a></div>`;
 case'stocks':return stocks(c);case'quote':return quote();case'countdown':return`<form class="widget-form" data-form="countdown"><input name="label" value="${esc(c.label||'Big day')}" aria-label="Event"><input type="date" name="date" value="${esc(c.date||'')}" aria-label="Date"><button>Set</button></form><div class="clock-face">${countdown(c.date)}</div><div class="clock-date">${esc(c.label||'Choose a date')}</div>`;
 case'tictactoe':return ttt(c);case'sudoku':return sudoku(c);
 case'photos':return`<form class="widget-form" data-form="photo"><input name="url" value="${esc(c.url||'')}" placeholder="Image URL"><button>Show</button></form>${c.url?`<img src="${esc(c.url)}" alt="Personal photo" style="width:100%;max-height:260px;object-fit:contain" referrerpolicy="no-referrer">`:'<p class="muted">Paste a public image URL to create your photo frame.</p>'}`;
 case'links':return`<div class="quick-links">${[['Gmail','https://mail.google.com'],['Calendar','https://calendar.google.com'],['Drive','https://drive.google.com'],['Photos','https://photos.google.com'],['Maps','https://maps.google.com'],['Books','https://books.google.com'],['News','https://news.google.com'],['YouTube','https://youtube.com']].map(x=>`<a target="_blank" rel="noopener" href="${x[1]}">${x[0]}</a>`).join('')}</div>`;default:return'<p>Gadget unavailable.</p>'}}
function calendar(offset,events){const now=new Date(),d=new Date(now.getFullYear(),now.getMonth()+offset,1),y=d.getFullYear(),m=d.getMonth(),first=d.getDay(),days=new Date(y,m+1,0).getDate();let cells='<td></td>'.repeat(first);for(let n=1;n<=days;n++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;cells+=`<td class="${offset===0&&n===now.getDate()?'today':''}" title="${esc((events.find(e=>e.date===iso)||{}).text||'')}">${n}${events.some(e=>e.date===iso)?'•':''}</td>`;if((first+n)%7===0)cells+='</tr><tr>'}return`<div class="month-head"><button class="link-button" data-month="-1">‹</button><b>${d.toLocaleString(undefined,{month:'long',year:'numeric'})}</b><button class="link-button" data-month="1">›</button></div><table class="calendar-grid"><thead><tr>${['Su','Mo','Tu','We','Th','Fr','Sa'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody><tr>${cells}</tr></tbody></table><form class="widget-form" data-form="event"><input type="date" name="date" required><input name="text" placeholder="Quick add event" required><button>Add</button></form>`}
const units={mi:['Miles',1609.344,'l'],km:['Kilometers',1000,'l'],m:['Meters',1,'l'],ft:['Feet',.3048,'l'],in:['Inches',.0254,'l'],lb:['Pounds',.453592,'w'],kg:['Kilograms',1,'w'],oz:['Ounces',.0283495,'w']};
function options(sel){return Object.entries(units).map(([k,v])=>`<option value="${k}" ${sel===k?'selected':''}>${v[0]}</option>`).join('')}function converter(c){return`<div class="converter"><div><input type="number" data-convert-input value="${esc(c.value||1)}"><select data-convert-from>${options(c.from||'mi')}</select></div><b>=</b><div><input data-convert-output readonly><select data-convert-to>${options(c.to||'km')}</select></div></div>`}
function stocks(c){const xs=c.symbols||['GOOG','AAPL','MSFT'];return`<form class="widget-form" data-form="stocks"><input name="symbol" placeholder="Ticker"><button>Add</button></form><table class="stock-table"><thead><tr><th>Symbol</th><th>Quote</th><th></th></tr></thead><tbody>${xs.map((s,i)=>`<tr><td><a target="_blank" rel="noopener" href="https://www.google.com/finance/quote/${esc(s)}:NASDAQ">${esc(s)}</a></td><td><a target="_blank" rel="noopener" href="https://www.google.com/finance/quote/${esc(s)}:NASDAQ">View live</a></td><td><button data-stock-remove="${i}">×</button></td></tr>`).join('')}</tbody></table>`}
function quote(){const qs=[['The future is already here — it is just not evenly distributed.','William Gibson'],['Simplicity is the ultimate sophistication.','Leonardo da Vinci'],['The best way to predict the future is to invent it.','Alan Kay'],['Stay hungry, stay foolish.','Stewart Brand']],q=qs[new Date().getDate()%qs.length];return`<blockquote class="quote">“${q[0]}”<cite>— ${q[1]}</cite></blockquote>`}function countdown(d){if(!d)return'—';const n=Math.ceil((new Date(`${d}T00:00:00`)-new Date())/86400000);return n<0?`${-n} days ago`:n===0?'Today!':`${n} days`}
function ttt(c){const b=c.board||Array(9).fill('');return`<div class="game-board">${b.map((x,i)=>`<button data-ttt="${i}">${x}</button>`).join('')}</div><p class="clock-date">${esc(c.winner?`${c.winner} wins!`:`${c.turn||'X'}'s turn`)} · <button class="link-button" data-game-reset>New game</button></p>`}function sudoku(c){const p=c.puzzle||[1,0,0,4,0,4,1,0,0,2,0,3,4,0,0,1];return`<div class="game-board" style="grid-template-columns:repeat(4,46px)">${p.map((n,i)=>n?`<button disabled style="height:46px">${n}</button>`:`<button data-sudoku="${i}" style="height:46px">${(c.answers||{})[i]||''}</button>`).join('')}</div><p class="clock-date">Mini 4×4 Sudoku · <button class="link-button" data-sudoku-reset>New puzzle</button></p>`}
function activate(w,node){if(w.type==='weather')weather(w,node);if(w.type==='news')news(w,node);if(w.type==='rss'&&w.config.url)rss(w,node);if(w.type==='clock')clock(w,node);if(w.type==='converter')convert(w,node)}
async function weather(w,node){const out=$('.weather-output',node),city=w.config.city||'New York';try{const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`).then(r=>r.json()),p=g.results?.[0];if(!p)throw Error('City not found');const d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${p.latitude}&longitude=${p.longitude}&current=temperature_2m,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=4`).then(r=>r.json());out.classList.remove('loading');out.innerHTML=`<b>${esc(p.name)}, ${esc(p.admin1||p.country||'')}</b><div class="weather-now"><span class="weather-icon">${weatherIcon(d.current.weather_code)}</span><span class="weather-temp">${Math.round(d.current.temperature_2m)}°F</span><span>Wind ${Math.round(d.current.wind_speed_10m)} mph</span></div><div class="weather-grid">${d.daily.time.map((day,i)=>`<div><b>${new Date(`${day}T12:00`).toLocaleDateString(undefined,{weekday:'short'})}</b><div>${weatherIcon(d.daily.weather_code[i])}</div><small>${Math.round(d.daily.temperature_2m_max[i])}° | ${Math.round(d.daily.temperature_2m_min[i])}°</small></div>`).join('')}</div>`}catch(e){out.className='weather-output error';out.textContent=`Weather unavailable: ${e.message}`}}
function weatherIcon(n){return n===0?'☀️':n<4?'⛅':n<60?'🌫️':n<80?'🌧️':n<90?'🌦️':'⛈️'}
async function news(w,node){const list=$('.news-list',node);try{const d=await fetch(`https://hn.algolia.com/api/v1/search?query=${encodeURIComponent(w.config.query||'technology')}&tags=story&hitsPerPage=8`).then(r=>r.json());list.innerHTML=d.hits.map(x=>`<li><a target="_blank" rel="noopener" href="${esc(x.url||`https://news.ycombinator.com/item?id=${x.objectID}`)}">${esc(x.title)}</a></li>`).join('')||'<li>No stories found.</li>'}catch{list.innerHTML='<li class="error">Headlines unavailable.</li>'}}
async function rss(w,node){const list=$('.rss-list',node);try{const d=await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(w.config.url)}`).then(r=>r.json());if(d.status!=='ok')throw Error();list.innerHTML=d.items.slice(0,8).map(x=>`<li><a target="_blank" rel="noopener" href="${esc(x.link)}">${esc(x.title)}</a></li>`).join('')}catch{list.innerHTML=`<li class="error">Feed blocked browser access. <a target="_blank" rel="noopener" href="${esc(w.config.url)}">Open directly</a>.</li>`}}
function clock(w,node){const tick=()=>{if(!node.isConnected)return;const z=w.config.zone==='local'||!w.config.zone?undefined:w.config.zone,n=new Date();$('[data-clock]',node).textContent=n.toLocaleTimeString([],{timeZone:z});$('[data-clock-date]',node).textContent=n.toLocaleDateString([],{timeZone:z,weekday:'long',month:'long',day:'numeric'});setTimeout(tick,1000)};tick()}
function convert(w,node){const input=$('[data-convert-input]',node),from=$('[data-convert-from]',node),to=$('[data-convert-to]',node),out=$('[data-convert-output]',node),calc=()=>{w.config={...w.config,value:input.value,from:from.value,to:to.value};out.value=units[from.value][2]===units[to.value][2]?(Number(input.value)*units[from.value][1]/units[to.value][1]).toFixed(4).replace(/\.?0+$/,''):'Incompatible';save()};[input,from,to].forEach(x=>x.addEventListener('input',calc));calc()}
function dropZones(){$$('.dashboard-column').forEach(col=>{col.ondragover=e=>{e.preventDefault();col.classList.add('drag-over')};col.ondragleave=()=>col.classList.remove('drag-over');col.ondrop=e=>{e.preventDefault();col.classList.remove('drag-over');if(!dragged)return;const ws=tab().widgets,item=ws.find(x=>x.instance===dragged);if(item)item.column=Number(col.dataset.column);const target=e.target.closest('.gadget');if(target&&target.dataset.instance!==dragged){const a=ws.findIndex(x=>x.instance===dragged),b=ws.findIndex(x=>x.instance===target.dataset.instance);ws.splice(b,0,ws.splice(a,1)[0])}dragged=null;render()}})}
document.addEventListener('dragstart',e=>{const g=e.target.closest('.gadget');if(g){dragged=g.dataset.instance;g.classList.add('dragging');e.dataTransfer.effectAllowed='move'}});document.addEventListener('dragend',e=>{e.target.closest('.gadget')?.classList.remove('dragging');dragged=null});
$('#dashboard').onclick=e=>{const box=e.target.closest('.gadget'),w=box&&widget(box.dataset.instance);if(!w)return;const a=e.target.closest('[data-action]')?.dataset.action;if(a==='remove'&&confirm(`Remove ${info(w.type).name}?`)){tab().widgets=tab().widgets.filter(x=>x!==w);render()}if(a==='minimize'){w.minimized=!w.minimized;render()}if(a==='expand')canvas(w);if(a==='settings')settings(w);const n=name=>e.target.dataset[name]!==undefined?Number(e.target.dataset[name]):null;let i;if((i=n('bookmarkRemove'))!==null){w.config.items.splice(i,1);render()}if((i=n('todoRemove'))!==null){w.config.items.splice(i,1);render()}if((i=n('todoCheck'))!==null){w.config.items[i].done=e.target.checked;render()}if((i=n('stockRemove'))!==null){w.config.symbols.splice(i,1);render()}if(e.target.dataset.month){w.config.monthOffset=(w.config.monthOffset||0)+Number(e.target.dataset.month);render()}if(e.target.dataset.calc)calc(w,e.target.dataset.calc);if((i=n('ttt'))!==null)play(w,i);if(e.target.hasAttribute('data-game-reset')){w.config={board:Array(9).fill(''),turn:'X'};render()}if((i=n('sudoku'))!==null){const x=prompt('Enter 1, 2, 3 or 4');if(/^[1-4]$/.test(x)){w.config.answers={...(w.config.answers||{}),[i]:x};render()}}if(e.target.hasAttribute('data-sudoku-reset')){w.config={puzzle:[0,2,0,4,3,0,1,0,0,1,0,3,4,0,2,0],answers:{}};render()}};
$('#dashboard').oninput=e=>{const w=widget(e.target.closest('.gadget')?.dataset.instance);if(!w)return;if(e.target.matches('[data-note]')){w.config.text=e.target.value;save()}if(e.target.matches('[data-timezone]')){w.config.zone=e.target.value;render()}};
$('#dashboard').onsubmit=e=>{e.preventDefault();const f=e.target,w=widget(f.closest('.gadget')?.dataset.instance);if(!w)return;const d=Object.fromEntries(new FormData(f));switch(f.dataset.form){case'weather':w.config.city=d.city;break;case'news':w.config.query=d.query;break;case'rss':w.config.url=d.url;break;case'bookmark':w.config.items=[...(w.config.items||[{label:'Google',url:'https://google.com'},{label:'Wikipedia',url:'https://wikipedia.org'}]),{label:d.label,url:url(d.url)}];break;case'todo':w.config.items=[...(w.config.items||[]),{text:d.task,done:false}];break;case'event':w.config.events=[...(w.config.events||[]),{date:d.date,text:d.text}];break;case'stocks':if(d.symbol)w.config.symbols=[...(w.config.symbols||['GOOG','AAPL','MSFT']),d.symbol.toUpperCase()];break;case'countdown':w.config={...w.config,...d};break;case'photo':w.config.url=d.url;break;case'maps':w.config.query=d.query;open(`https://maps.google.com/?q=${encodeURIComponent(d.query)}`,'_blank');break;case'translate':w.config.text=d.text;open(`https://translate.google.com/?sl=auto&tl=${encodeURIComponent(d.lang)}&text=${encodeURIComponent(d.text)}&op=translate`,'_blank');break;case'youtube':w.config.query=d.query;open(`https://www.youtube.com/results?search_query=${encodeURIComponent(d.query)}`,'_blank');break;case'wikipedia':w.config.query=d.query;open(`https://en.wikipedia.org/w/index.php?search=${encodeURIComponent(d.query)}`,'_blank');break;case'dictionary':w.config.query=d.query;open(`https://www.google.com/search?q=define%3A${encodeURIComponent(d.query)}`,'_blank');break}render()};
function url(x){try{return new URL(x.includes('://')?x:`https://${x}`).href}catch{return'#'}}function calc(w,k){let d=w.config.display||'0';if(k==='C')d='0';else if(k==='⌫')d=d.length>1?d.slice(0,-1):'0';else if(k==='='){try{const x=d.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-');if(!/^[0-9+*/().\- ]+$/.test(x))throw Error();d=String(Function(`"use strict";return (${x})`)())}catch{d='Error'}}else d=(d==='0'||d==='Error')?k:d+k;w.config.display=d;render()}function play(w,i){const b=w.config.board||Array(9).fill(''),t=w.config.turn||'X';if(b[i]||w.config.winner)return;b[i]=t;w.config.board=b;w.config.winner=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(l=>l.every(x=>b[x]===t))?t:'';w.config.turn=t==='X'?'O':'X';render()}
function dialog(html){$('#dialog-content').innerHTML=html;$('#app-dialog').showModal()}function canvas(w){dialog(`<section class="canvas-widget"><h1 class="dialog-title">${info(w.type).icon} ${esc(w.config.title||info(w.type).name)}</h1><div class="gadget-content">${contentFor(w)}</div></section>`);queueMicrotask(()=>activate(w,$('#dialog-content')))}function settings(w){dialog(`<h1 class="dialog-title">Gadget settings</h1><div class="dialog-row"><label>Title</label><input id="setting-title" value="${esc(w.config.title||info(w.type).name)}"></div><div class="dialog-actions"><button class="dialog-button" id="save-settings">Save</button></div>`);$('#save-settings').onclick=e=>{e.preventDefault();w.config.title=$('#setting-title').value.trim();$('#app-dialog').close();render()}}
function renderCatalog(){const cats=['Featured',...new Set(catalog.map(x=>x.category))];$('#catalog-categories').innerHTML=cats.map(x=>`<button class="${x===category?'active':''}" data-category="${x}">${x}</button>`).join('');const q=$('#catalog-search').value.toLowerCase(),items=catalog.filter(x=>(category==='Featured'||x.category===category)&&`${x.name} ${x.desc}`.toLowerCase().includes(q));$('#catalog-results').innerHTML=items.map(x=>`<article class="catalog-card"><span class="catalog-icon">${x.icon}</span><div><h2>${x.name}</h2><p>${x.desc}</p><small>${x.category}</small></div><button data-add-gadget="${x.id}">Add it now</button></article>`).join('')||'<p>No gadgets found.</p>'}function showCatalog(show=true){$('#gadget-catalog').hidden=!show;if(show){renderCatalog();$('#gadget-catalog').scrollIntoView({behavior:'smooth'})}}
$('#add-stuff').onclick=()=>showCatalog();$('#empty-add').onclick=()=>showCatalog();$('#gadget-catalog').onclick=e=>{if(e.target.dataset.close==='catalog')showCatalog(false);if(e.target.dataset.category){category=e.target.dataset.category;renderCatalog()}if(e.target.dataset.addGadget){const counts=[...Array(tab().layout)].map((_,i)=>tab().widgets.filter(w=>w.column===i).length),col=counts.indexOf(Math.min(...counts));tab().widgets.push({instance:uid(),type:e.target.dataset.addGadget,column:col,config:{},minimized:false});render();renderCatalog();toast(`${info(e.target.dataset.addGadget).name} added`)}};$('#catalog-search').oninput=renderCatalog;$('#search-catalog').onclick=renderCatalog;
$('#custom-feed-button').onclick=()=>{dialog(`<h1 class="dialog-title">Add feed or gadget</h1><p>Type or paste a public RSS or Atom URL.</p><div class="dialog-row"><label>URL</label><input id="feed-url" value="https://"></div><div class="dialog-actions"><button class="dialog-button" id="save-feed">Add</button></div>`);$('#save-feed').onclick=e=>{e.preventDefault();tab().widgets.push({instance:uid(),type:'rss',column:0,config:{url:$('#feed-url').value},minimized:false});$('#app-dialog').close();showCatalog(false);render()}};
$('#tabs').onclick=e=>{const b=e.target.closest('.tab');if(!b)return;if(e.target.classList.contains('tab-menu')){const t=state.tabs.find(x=>x.id===b.dataset.tab);dialog(`<h1 class="dialog-title">Edit tab</h1><div class="dialog-row"><label>Tab name</label><input id="tab-name" value="${esc(t.name)}"></div><div class="dialog-actions"><button class="dialog-button" id="rename-tab">Save</button>${state.tabs.length>1?'<button class="dialog-button" id="delete-tab">Delete tab</button>':''}</div>`);$('#rename-tab').onclick=x=>{x.preventDefault();t.name=$('#tab-name').value.trim()||t.name;$('#app-dialog').close();render()};if($('#delete-tab'))$('#delete-tab').onclick=x=>{x.preventDefault();if(confirm(`Delete ${t.name} and its gadgets?`)){state.tabs=state.tabs.filter(a=>a!==t);state.activeTab=state.tabs[0].id;$('#app-dialog').close();render()}}}else{state.activeTab=b.dataset.tab;render()}};
$('#add-tab').onclick=()=>{dialog(`<h1 class="dialog-title">Add a tab</h1><div class="dialog-row"><label>Tab name</label><input id="new-tab-name" placeholder="e.g. sports, news, music"></div><label><input type="checkbox" id="lucky-tab" checked> I'm feeling lucky — add suggested gadgets</label><div class="dialog-actions"><button class="dialog-button" id="create-tab">Add</button></div>`);$('#create-tab').onclick=e=>{e.preventDefault();const name=$('#new-tab-name').value.trim()||'New tab',id=uid(),map={news:['news','rss','weather'],sports:['news','weather','todo'],finance:['stocks','news','calculator'],music:['youtube','rss','quote'],games:['tictactoe','sudoku','quote']},types=$('#lucky-tab').checked?(map[name.toLowerCase()]||['links','notes','weather']):[];state.tabs.push({id,name,layout:3,widgets:types.map((type,i)=>({instance:uid(),type,column:i%3,config:{},minimized:false}))});state.activeTab=id;$('#app-dialog').close();render()}};
$('#theme-button').onclick=()=>{const current=tab().theme||state.theme;dialog(`<h1 class="dialog-title">Select a theme for this tab</h1><div class="theme-grid">${themes.map(([id,name])=>`<button class="theme-choice theme-${id} ${current===id?'active':''}" data-theme-choice="${id}"><span>${name}</span></button>`).join('')}</div>`);$$('[data-theme-choice]',$('#dialog-content')).forEach(b=>b.onclick=e=>{e.preventDefault();tab().theme=b.dataset.themeChoice;$('#app-dialog').close();render()})};
$('#layout-button').onclick=()=>{const t=tab();dialog(`<h1 class="dialog-title">Choose a layout</h1><div class="layout-grid">${[1,2,3].map(n=>`<button class="layout-choice ${t.layout===n?'active':''}" data-layout="${n}" aria-label="${n} columns">${'<i></i>'.repeat(n)}</button>`).join('')}</div>`);$$('[data-layout]',$('#dialog-content')).forEach(b=>b.onclick=e=>{e.preventDefault();t.layout=Number(b.dataset.layout);t.widgets.forEach(w=>w.column=Math.min(w.column,t.layout-1));$('#app-dialog').close();render()})};
$('#reset-dashboard').onclick=()=>{if(confirm('Reset every tab, gadget and theme?')){localStorage.removeItem(KEY);state=structuredClone(defaults);render();toast('Dashboard reset')}};$('#set-home').onclick=()=>dialog('<h1 class="dialog-title">Make iGoogle your homepage</h1><p>Browser security prevents websites from changing your homepage automatically. Open browser settings and set this page as the home page or new-tab URL.</p>');$('#more-services').onclick=()=>$('#services-menu').hidden=!$('#services-menu').hidden;document.addEventListener('click',e=>{if(!e.target.closest('#more-services')&&!e.target.closest('#services-menu'))$('#services-menu').hidden=true});$('#lucky-search').onclick=()=>{const q=$('#search-query').value.trim();if(q)location.href=`https://www.google.com/search?btnI=1&q=${encodeURIComponent(q)}`};render();
